docs: create chaos mesh workflow
chaos-mesh/website-zh pull request #22
Opened 2021-05-21 06:12 UTC by STRRL

Signed-off-by: STRRL <str_ruiling@outlook.com>

2021-05-25 09:14 UTC, g1eny0ung commented on docs/create-chaos-mesh-workflow.md
> +其中 `templates` 定义了实验中的各个步骤, `entry` 定义了 Workflow 执行时的入口.
`.` => `。`

2021-05-31 12:22 UTC, cwen0 commented on docs/create-chaos-mesh-workflow.md
> +        scheduler:
以 2.0 版本为基础

2021-05-31 12:22 UTC, cwen0 commented on docs/create-chaos-mesh-workflow.md
> +## Chaos Mesh Workflow 简介
感觉可以把串并行的那个文档和到这个文档里，另外字段可以单拎出来去介绍

2021-06-01 02:39 UTC, STRRL commented on docs/create-chaos-mesh-workflow.md
> +## Chaos Mesh Workflow 简介
这也是我在写文档是比较困惑的一个点；

我的理解是我们的这个文档中应该着重于 example 和粗浅的概念解释. 详细字段的介绍应该放到 Reference 文档中介绍.

2021-06-22 06:17 UTC, cwen0 commented on docs/create-chaos-mesh-workflow.md
> +## Chaos Mesh Workflow 简介
现在我们还没有 reference 文档，如果字段不是非常多的的话，我觉得一个文档就可以了

2021-06-22 06:18 UTC, cwen0 commented on docs/create-chaos-mesh-workflow.md
> +## Chaos Mesh Workflow 简介
这个的字段介绍可以单独一个文档，或者嵌入到这个文档里，放在最后面

2021-06-22 09:20 UTC, STRRL commented on docs/create-chaos-mesh-workflow.md
> +## Chaos Mesh Workflow 简介
updated PTAL @cwen0 !

2021-06-24 08:29 UTC, fewdan requested changes

2021-06-24 08:29 UTC, fewdan commented on docs/create-chaos-mesh-workflow.md
> +`templateType: Parallel` 代表节点的类型为并行； `duration: 240s` 代表这个节点下的所有并行实验预期在 240 秒内执行完成， 否则将超时； `tasks` 中代表了将要并行执行的其他 template 的名称。
这边应该改成  deadline: 240s 代表xxx

2021-06-24 08:29 UTC, fewdan commented on docs/create-chaos-mesh-workflow.md
> +`templateType: PodChaos` 代表节点的类型为 PodChaos 实验； `duration: 40s` 代表当前 Chaos 实验将持续 40 秒； `podChaos` 字段是 PodChaos 实验的定义；
同上

2021-06-24 09:53 UTC, STRRL commented on docs/create-chaos-mesh-workflow.md
> +`templateType: Parallel` 代表节点的类型为并行； `duration: 240s` 代表这个节点下的所有并行实验预期在 240 秒内执行完成， 否则将超时； `tasks` 中代表了将要并行执行的其他 template 的名称。
fixed PTAL! @fewdan

2021-06-29 08:46 UTC, fewdan approved these changes
LGTM

2021-06-29 09:56 UTC, g1eny0ung commented on docs/create-chaos-mesh-workflow.md
> +注意，当在 Workflow 中建立有持续时间的 Chaos 时，需要将持续时间填写到外层的 `deadline` 字段中，而不是使用 Chaos 中的 `duration` 字段。
这个注意用 `:::note` 那个格式吧。

2021-06-29 09:56 UTC, g1eny0ung commented on docs/create-chaos-mesh-workflow.md
> +目前在 `expression` 中提供了两个魔法值：
这里说`魔法值`是不是不太好，我参考了一下 GitHub Action，他们会用`上下文变量`这个翻译。

2021-06-30 03:34 UTC, STRRL commented
updated! PTAL @g1eny0ung

2021-06-30 03:36 UTC, g1eny0ung approved these changes
LGTM

2021-06-30 03:44 UTC, STRRL commented
checking markdown links failed because "http://netgroup.uniroma2.it/twiki/bin/view.cgi/Main/NetemCLG" in 503.

Will try to rerun that check later,(after that reference link is available)

2021-06-30 03:48 UTC, g1eny0ung commented
> checking markdown links failed because "http://netgroup.uniroma2.it/twiki/bin/view.cgi/Main/NetemCLG" in 503.
> 
> Will try to rerun that check later,(after that reference link is available)

This can be ignored. it's frequently inaccurate.

2021-06-30 04:04 UTC, TomShawn commented on docs/create-chaos-mesh-workflow.md
> +
如果现在这一部分内容尚未准备好，建议暂时移除这个标题，等内容 ready 后再一起加进来。

2021-06-30 04:04 UTC, TomShawn commented on docs/create-chaos-mesh-workflow.md
> +在模拟真实世界中的失败时，伴随着持续验证，最好是构建一系列的故障，而不是执行一个独立的混沌故障注入操作。
```suggestion
在 Chaos Mesh 中模拟真实的系统故障时，通常伴随着持续验证。你可能希望在 Chaos Mesh 平台上构建一系列故障，而不是执行单个独立的混沌故障注入操作。
```

2021-06-30 04:04 UTC, TomShawn commented on docs/create-chaos-mesh-workflow.md
> +Chaos Mesh Workflow 是一个内置的工作流引擎， 允许你串行/并行地执行多种不同的 Chaos 实验， 用于模拟生产级别的错误。
```suggestion
为满足该需求，Chaos Mesh 提供了 Chaos Mesh Workflow，一个内置的工作流引擎。使用该引擎，你可以串行或并行地执行多种不同的 Chaos 实验， 用于模拟生产级别的错误。
```

2021-06-30 04:04 UTC, TomShawn commented on docs/create-chaos-mesh-workflow.md
> +- 在串行编排中进行健康检查， 使用条件分支决定是否执行剩下的步骤
```suggestion
- 在串行编排中进行健康检查，使用条件分支决定是否执行剩下的步骤
```

2021-06-30 04:04 UTC, TomShawn commented on docs/create-chaos-mesh-workflow.md
> +Chaos Mesh Workflow 在设计时一定程度上参考了 Argo Workflow， 如果您熟悉 Argo Workflow 您也能很快地上手 Chaos Mesh Workflow。
上面的内容是 Chaos Mesh Workflow 的概念介绍，下面才是如何创建 Workflow。建议将这一段移到 Line 36 下面。另外，个人觉得这句话对读者意义不大，似乎可以删除。
```suggestion
Chaos Mesh Workflow 在设计时一定程度上参考了 Argo Workflow。如果您熟悉 Argo Workflow 您也能很快地上手 Chaos Mesh Workflow。
```

2021-06-30 04:04 UTC, TomShawn commented on docs/create-chaos-mesh-workflow.md
> +:::
Note 一般是用于提醒用户以上内容中需要注意的方面，会切实影响到用户操作或理解的。如果只是单纯的补充信息，建议不写进 Note。

2021-06-30 04:04 UTC, TomShawn commented on docs/create-chaos-mesh-workflow.md
> +类似于各种类型的 Chaos 对象， Workflow 同样作为 CRD 存在于 kubernetes 集群中， 也可以使用 `kubectl create -f <workflow.yaml>` 创建。
```suggestion
Workflow 类似于各种类型的 Chaos 对象，同样作为 CRD 存在于 kubernetes 集群中。你可以使用 `kubectl create -f <workflow.yaml>` 创建 Chaos Mesh Workflow。以下为创建的具体示例。
```

2021-06-30 04:04 UTC, TomShawn commented on docs/create-chaos-mesh-workflow.md
> +
```suggestion
```

2021-06-30 04:04 UTC, TomShawn commented on docs/create-chaos-mesh-workflow.md
> +使用本地 YAML 文件创建 Workflow:
```suggestion
使用本地 YAML 文件创建 Workflow：
```

2021-06-30 04:04 UTC, TomShawn commented on docs/create-chaos-mesh-workflow.md
> +使用网络上的 YAML 创建 Workflow:
```suggestion
使用网络上的 YAML 文件创建 Workflow：
```

2021-06-30 04:04 UTC, TomShawn commented on docs/create-chaos-mesh-workflow.md
> +一个简单的 Workflow 定义如下所示， 这个 Workflow 将会同时注入 `StressChaos`， `NetworkChaos` 与 `PodChaos`：
```suggestion
一个简单的 Workflow YAML 文件定义如下所示，这个 Workflow 将会同时注入 `StressChaos`、`NetworkChaos` 与 `PodChaos`：
```

2021-06-30 04:04 UTC, TomShawn commented on docs/create-chaos-mesh-workflow.md
> +其中 `templates` 定义了实验中的各个步骤， `entry` 定义了 Workflow 执行时的入口。
```suggestion
其中 `templates` 定义了实验中的各个步骤，`entry` 定义了 Workflow 执行时的入口。
```

2021-06-30 04:04 UTC, TomShawn commented on docs/create-chaos-mesh-workflow.md
> +`templates` 中的每个元素都代表了一个 Workflow 的步骤， 例如:
```suggestion
`templates` 中的每个元素都代表了一个 Workflow 的步骤，例如:
```

2021-06-30 04:04 UTC, TomShawn commented on docs/create-chaos-mesh-workflow.md
> +`templateType: Parallel` 代表节点的类型为并行； `deadline: 240s` 代表这个节点下的所有并行实验预期在 240 秒内执行完成， 否则将超时； `tasks` 中代表了将要并行执行的其他 template 的名称。
上面模板里没看到 task 字段
```suggestion
`templateType: Parallel` 代表节点的类型为并行；`deadline: 240s` 代表这个节点下的所有并行实验预期在 240 秒内执行完成，否则将超时；`children` 代表将要并行执行的其他 template 名称。
```

2021-06-30 04:04 UTC, TomShawn commented on docs/create-chaos-mesh-workflow.md
> +`templateType: PodChaos` 代表节点的类型为 PodChaos 实验； `deadline: 40s` 代表当前 Chaos 实验将持续 40 秒； `podChaos` 字段是 PodChaos 实验的定义；
```suggestion
`templateType: PodChaos` 代表节点的类型为 PodChaos 实验；`deadline: 40s` 代表当前 Chaos 实验将持续 40 秒；`podChaos` 字段是 PodChaos 实验的定义。
```

2021-06-30 04:04 UTC, TomShawn commented on docs/create-chaos-mesh-workflow.md
> +与 Chaos Dashboard 相比， 通过 YAML 与 `kubectl` 创建 Workflow 会更加灵活； 你可以对串行/并行编排进行嵌套， 声明复杂的编排， 甚至可以与条件分支组合达到循环的效果。
前面没有 Chaos Dashboard 相关内容。
```suggestion
通过 YAML 文件与 `kubectl` 创建 Workflow 较为灵活，你可以对串行活并行编排进行嵌套，声明复杂的编排，甚至可以与条件分支组合达到循环的效果。
```

2021-06-30 05:43 UTC, cwen0 commented
@STRRL PTAL

2021-07-06 10:05 UTC, STRRL commented on docs/create-chaos-mesh-workflow.md
> +
好的。 完整的特性将于这周发布的 v2.0.0-beta.3 中带入，后面再更新这个文档。：）

2021-07-06 10:06 UTC, STRRL commented on docs/create-chaos-mesh-workflow.md
> +:::
好的，那我将直接使用普通的文字描述吧。

FYI @g1eny0ung

2021-07-08 06:11 UTC, cwen0 commented
/merge

2021-07-08 06:11 UTC, merged