docs: add simulate JVMChaos
chaos-mesh/website-zh pull request #32
Opened 2021-06-07 11:50 UTC by STRRL

Signed-off-by: STRRL <str_ruiling@outlook.com>

2021-06-09 07:21 UTC, WangXiangUSTC commented on docs/simulate-jvm-application-chaos.md
> +- 命名空间下的所有容器中的 JVM 都会在启动阶段加载 java agent, JVMChaos 在被删除后也不会卸载 java agent。若考虑到 java agent 可能对程序行为或性能带来的影响，期望清理 java agnet，请将工作负载移出该命名空间；
`请将工作负载移出该命名空间` 是指负载不施加到曾经注入过 jvm chaos 的 pod？

2021-06-09 07:21 UTC, WangXiangUSTC commented on docs/simulate-jvm-application-chaos.md
> +|action|string|表示具体的故障类型，支持delay、return、script、cfl、oom、ccf、tce、cpf、tde、tpf|无|是|return|
这些故障类型是否需要解释，或者给链接

2021-06-15 10:04 UTC, STRRL commented on docs/simulate-jvm-application-chaos.md
> +- 命名空间下的所有容器中的 JVM 都会在启动阶段加载 java agent, JVMChaos 在被删除后也不会卸载 java agent。若考虑到 java agent 可能对程序行为或性能带来的影响，期望清理 java agnet，请将工作负载移出该命名空间；
负载 指的是被注入 Chaos 的应用；这里描述的行为其实就比如 将应用的 Deployment 移出这个 namespace.

2021-06-15 10:18 UTC, STRRL commented on docs/simulate-jvm-application-chaos.md
> +|action|string|表示具体的故障类型，支持delay、return、script、cfl、oom、ccf、tce、cpf、tde、tpf|无|是|return|
好的，我解释一下行为然后再放一个 chaos blade 的链接吧。

2021-06-18 01:49 UTC, STRRL commented on docs/simulate-jvm-application-chaos.md
> +|action|string|表示具体的故障类型，支持delay、return、script、cfl、oom、ccf、tce、cpf、tde、tpf|无|是|return|
更新过了， PTAL！

2021-06-22 06:54 UTC, WangXiangUSTC approved these changes
LGTM

2021-06-22 07:39 UTC, Joyinqin requested changes

2021-06-22 07:39 UTC, Joyinqin commented on docs/simulate-jvm-application-chaos.md
> +目前 Chaos Mesh 使用 [MutatingAdmissionWebhook](https://kubernetes.io/zh/docs/reference/access-authn-authz/admission-controllers/#mutatingadmissionwebhook) 修改对 Pod 的定义，通过 [Init 容器](https://kubernetes.io/
```suggestion
目前 Chaos Mesh 使用 [MutatingAdmissionWebhook](https://kubernetes.io/zh/docs/reference/access-authn-authz/admission-controllers/#mutatingadmissionwebhook) 修改对 Pod 的定义，通过 [Init 容器](https://kubernetes.io/zh/docs/concepts/workloads/pods/init-containers/)加载 java agnet，并非运行时加载 java agent。因此在使用时存在如下限制：
```

2021-06-22 07:39 UTC, Joyinqin commented on docs/simulate-jvm-application-chaos.md
> +- 命名空间下的所有容器中的 JVM 都会在启动阶段加载 java agent, JVMChaos 在被删除后也不会卸载 java agent。若考虑到 java agent 可能对程序行为或性能带来的影响，期望清理 java agnet，请将工作负载移出该命名空间；
```suggestion
- Kubernetes 需要启用 Webhook 支持。
- 在为命名空间配置 MutatingAdmissionWebhook 之前已经存在 Pod，不会受到 JVMChaos 影响。
- 命名空间下的所有容器中的 JVM 都会在启动阶段加载 java agent，VMChaos 在被删除后也不会卸载 java agent。若考虑到 java agent 可能对程序行为或性能带来的影响，期望清理 java agnet，请将工作负载移出该命名空间。
```

2021-06-22 07:39 UTC, Joyinqin commented on docs/simulate-jvm-application-chaos.md
> +建立应用所在的命名空间:
```suggestion
建立应用所在的命名空间：
```

2021-06-22 07:39 UTC, Joyinqin commented on docs/simulate-jvm-application-chaos.md
> +为命名空间 `app` 增加 label `admission-webhook=enabled`, 允许 Chaos Mesh 的 MutatingAdmissionWebhook 修改该命名空间下的 Pod.
```suggestion
为命名空间 `app` 增加 label `admission-webhook=enabled`，允许 Chaos Mesh 的 MutatingAdmissionWebhook 修改该命名空间下的 Pod。
```

2021-06-22 07:39 UTC, Joyinqin commented on docs/simulate-jvm-application-chaos.md
> +为 JVMChaos 所需要的修改行为准备模板:
```suggestion
为 JVMChaos 所需要的修改行为准备模板：
```

2021-06-22 07:39 UTC, Joyinqin commented on docs/simulate-jvm-application-chaos.md
> +这里使用 [jvm-chaos-demo](https://github.com/chaos-mesh/jvm-chaos-demo) 作为被测应用，是一个简单的 Spring Boot 应用。 被测应用定义在 `example/jvm/app.yaml` 中，内容如下：
```suggestion
[jvm-chaos-demo](https://github.com/chaos-mesh/jvm-chaos-demo) 是一个简单的 Spring Boot 应用，此处作为被测应用。被测应用定义在 `example/jvm/app.yaml` 中，内容如下：
```

2021-06-22 07:39 UTC, Joyinqin commented on docs/simulate-jvm-application-chaos.md
> +建立应用 Deployment:
```suggestion
建立应用 Deployment：
```

2021-06-22 07:39 UTC, Joyinqin commented on docs/simulate-jvm-application-chaos.md
> +执行 `kubectl -n app get pods`, 预期能够观察到命名空间 `app` 中出现 `1` 个名称形如 `springboot-jvmchaos-demo-777d94c5b9-7t7l2` 的 Pod，等待其 `READY` 为 `1/1` 后进行下一步
```suggestion
执行 `kubectl -n app get pods`，预期能够观察到命名空间 `app` 中出现 `1` 个名称形如 `springboot-jvmchaos-demo-777d94c5b9-7t7l2` 的 Pod，等待其 `READY` 为 `1/1` 后进行下一步。
```

2021-06-22 07:39 UTC, Joyinqin commented on docs/simulate-jvm-application-chaos.md
> +在另外一个 shell session 中使用 curl 或者直接使用浏览器访问 `http://localhost:8080/hello`, 预期返回 `Hello firend`：
```suggestion
在另外一个 shell session 中使用 curl 或者直接使用浏览器访问 `http://localhost:8080/hello`，预期返回 `Hello firend`：
```

2021-06-22 07:39 UTC, Joyinqin commented on docs/simulate-jvm-application-chaos.md
> +指定返回值的 JVMChaos 内容如下:
```suggestion
指定返回值的 JVMChaos 内容如下：
```

2021-06-22 07:39 UTC, Joyinqin commented on docs/simulate-jvm-application-chaos.md
> +关于 action 的取值的含义，可参考:
```suggestion
关于 action 的取值的含义，可参考：
```

2021-06-22 07:39 UTC, Joyinqin commented on docs/simulate-jvm-application-chaos.md
> +|target|string|传递给 `chaosblade-exec-jvm` 的参数，代表 JVMChaos 的目标，支持servlet、psql、jvm、jedis、http、dubbo、rocketmq、tars、mysql、druid、redisson、rabbitmq、mongodb|无|是|jvm|
```suggestion
|action|string|表示具体的故障类型，支持 delay、return、script、cfl、oom、ccf、tce、cpf、tde、tpf。|无|是|return|
|mode|string|表示选择 Pod 的方式，支持 one、all、fixed、fixed-percent、random-max-percent。|无|是|one|
|value|string|取决与 mode 的取值，为 mode 提供参数|无|否|2|
|target|string|传递给 `chaosblade-exec-jvm` 的参数，代表 JVMChaos 的目标，支持 servlet、psql、jvm、jedis、http、dubbo、rocketmq、tars、mysql、druid、redisson、rabbitmq、mongodb。|无|是|jvm|
```

2021-06-22 07:39 UTC, Joyinqin commented on docs/simulate-jvm-application-chaos.md
> +使用 curl 或者直接使用浏览器访问 http://localhost:8080/hello, 预期返回 `hello chaos mesh!`：
```suggestion
使用 curl 或者直接使用浏览器访问 http://localhost:8080/hello，预期返回 `hello chaos mesh!`：
```

2021-06-22 07:39 UTC, Joyinqin commented on docs/simulate-jvm-application-chaos.md
> +关于传递给 `chaosblade-exec-jvm` 的参数，Chaos Mesh 会将 `flags` 与 `matchers` 中的所有字段合并后作为请求体发送给 `chaosblade-exec-jvm`，具体可参考 [chaosblade-exec-jvm/协议篇.md](https://github.com/chaosblade-io/chaosblade-dev-doc/blob/
1.这个md文档文件名不能用汉字 2. 并且这里应该是相对链接，不是绝对链接哦。

2021-06-22 07:39 UTC, Joyinqin commented on docs/simulate-jvm-application-chaos.md
> +JVMChaos 能向目标容器中的 JVM 注入故障，适用于任何使用 JVM 作为运行时的应用。目前 JVMChaos 借助于 [chaosblade-exec-jvm](https://github.com/chaosblade-io/chaosblade-exec-jvm) 实现对 JVM 的错误注入，主要支持以下类型的故障：
```suggestion
JVMChaos 能向目标容器中的 JVM 注入故障，适用于任何使用 JVM 作为运行时的应用。目前 JVMChaos 借助 [chaosblade-exec-jvm](https://github.com/chaosblade-io/chaosblade-exec-jvm) 实现对 JVM 的错误注入，主要支持以下类型的故障：
```

2021-06-22 07:39 UTC, Joyinqin commented on docs/simulate-jvm-application-chaos.md
> +另外 JVM 目前无法通过 Chaos Dashboard 创建。
```suggestion
另外，目前无法通过 Chaos Dashboard 创建 JVM。
```

2021-06-22 07:39 UTC, Joyinqin commented on docs/simulate-jvm-application-chaos.md
> +下面将以指定返回值为例，展示 JVMChaos 的使用方法与效果。以下内容中设计的 yaml 文件均可在 [examples/jvm](https://github.com/chaos-mesh/chaos-mesh/tree/master/examples/jvm) 中找到，以下步骤默认的工作路径也是在 `examples/jvm`。 默认 Chaos Mesh 安装的 namespace 为
```suggestion
下面将以指定返回值为例，展示 JVMChaos 的使用方法与效果。以下内容中涉及的 yaml 文件均可在 [examples/jvm](https://github.com/chaos-mesh/chaos-mesh/tree/master/examples/jvm) 中找到，以下步骤默认的工作路径也是在 `examples/jvm` 中。 默认 Chaos Mesh 安装的命名空间为 `chaos-testing`。
```

2021-06-22 07:39 UTC, Joyinqin commented on docs/simulate-jvm-application-chaos.md
> +它将修改 `hello` 方法的返回值为字符串 `hello chaos mesh!`.
```suggestion
JVMChaos 将 `hello` 方法的返回值修改为字符串 `hello chaos mesh!`。
```

2021-06-22 07:50 UTC, Joyinqin reviewed
minor edits, rest lgtm~

2021-06-22 08:13 UTC, STRRL commented on docs/simulate-jvm-application-chaos.md
> +关于传递给 `chaosblade-exec-jvm` 的参数，Chaos Mesh 会将 `flags` 与 `matchers` 中的所有字段合并后作为请求体发送给 `chaosblade-exec-jvm`，具体可参考 [chaosblade-exec-jvm/协议篇.md](https://github.com/chaosblade-io/chaosblade-dev-doc/blob/
> 1.这个md文档文件名不能用汉字

改成: 具体可参考 chaosblade-exec-jvm 文档 [协议篇.md](url). 如何?

> 2. 并且这里应该是相对链接，不是绝对链接哦。

这里链接到了别的 repo, 是外部的文档, 貌似只能使用绝对链接.

2021-06-22 08:45 UTC, Joyinqin approved these changes

2021-06-23 05:38 UTC, merged