docs: add upgrade-to-2.0
chaos-mesh/website-zh pull request #37
Opened 2021-06-18 09:02 UTC by AsterNighT

Signed-off-by: AsterNighT <klxjt99@outlook.com>

2021-06-18 09:03 UTC, AsterNighT commented
I suppose there's extra work for this?

2021-06-21 06:48 UTC, fewdan commented on docs/upgrade-to-2.0.md
> +如果在升级过程中遇到任何问题，我们很乐意帮助解决。请将命令行输出一并提交至 slack 或新建 github issue 。
我觉得这边可以直接放一下slack和github issue的链接？

2021-06-28 02:04 UTC, qiancai approved these changes

2021-06-28 02:04 UTC, qiancai commented on docs/upgrade-to-2.0.md
> +Chaos Mesh 2.0 修复了许多问题，同时引入了一些新功能。我们对代码进行了一定程度上的重构，导致 Chaos Mesh 1.x 的用户需要一些额外的操作来升级到 2.0 。本文将介绍从 Chaos Mesh 1.x 升级至 2.0 的详细步骤。
```suggestion
本文将介绍从 Chaos Mesh 1.x 升级至 2.0 的详细步骤。Chaos Mesh 2.0 引入了一些新功能，并修复了许多问题。Chaos Mesh 2.0 重构了一部分代码，因此需要做一些额外的操作从 Chaos Mesh 1.x 来升级到 2.0。
```

2021-06-28 02:04 UTC, qiancai commented on docs/upgrade-to-2.0.md
> +我们提供了一个升级脚本来简化升级过程。你可以在 tools/schedule-migration 找到它们。为使用这一工具，我们建议您将 Chaos Mesh 项目克隆至本地，或是从（这里应该有一个打包好的链接）获取。你需要拥有 go 编译环境以编译升级工具。
```suggestion
为了简化升级过程，Chaos Mesh 2.0 为你提供了一个升级工具 `migrate.sh`（位于 tools/schedule-migration 路径下）。

为使用这一工具，我们建议将 Chaos Mesh 项目克隆至本地，或是从（这里应该有一个打包好的链接）获取。你需要拥有 Go 编译环境用于编译升级工具。
```

2021-06-28 02:04 UTC, qiancai commented on docs/upgrade-to-2.0.md
> +我们提供了一个升级脚本来简化升级过程。你可以在 tools/schedule-migration 找到它们。为使用这一工具，我们建议您将 Chaos Mesh 项目克隆至本地，或是从（这里应该有一个打包好的链接）获取。你需要拥有 go 编译环境以编译升级工具。
请问这个部分可以再写具体些吗？这个工具的链接是在 Github 上吗？编译好升级工具后，就可以直接运行了吗？是否有需要注意的地方？

2021-06-28 02:04 UTC, qiancai commented on docs/upgrade-to-2.0.md
> +
在运行此脚本时，对旧版本的实验 YAML 文件的存放路径有要求吗？

2021-06-28 02:04 UTC, qiancai commented on docs/upgrade-to-2.0.md
> +如果使用 helm 升级 Chaos Mesh ，可能需要手动升级 CRD 。无论如何，手动升级一次 CRD 能最大程度保证升级成功。运行：
```suggestion
当使用 Helm 升级 Chaos Mesh 时，为了能最大程度保证升级成功，请运行以下命令手动升级一次 CRD：
```

2021-06-28 02:04 UTC, qiancai commented on docs/upgrade-to-2.0.md
> +由于 2.0 的改动较大，我们推荐在卸载 1.x 后重新进行安装。具体安装步骤参见（此处应有安装教程链接）。
```suggestion
由于 2.0 的改动较大，我们推荐在卸载 1.x 后重新进行安装。具体安装步骤，请参考[使用 Helm 安装（生产推荐）](/production-installation-using-helm.md)。
```

2021-06-28 02:04 UTC, qiancai commented on docs/upgrade-to-2.0.md
> +在当前目录下出现了许多yaml文件，这些就是被导出的实验。导出的实验已经被自动升级。
```suggestion
在当前目录下出现了许多 YAML 文件，这些就是被导出的实验文件。导出的实验已经被自动升级。
```

2021-06-28 02:04 UTC, qiancai commented on docs/upgrade-to-2.0.md
> +Chaos Mesh 2.0 对实验定义进行了一些修改，需要对旧实验进行更新后才能继续使用。在导出实验的基础上，在同一目录下，运行：
```suggestion
Chaos Mesh 2.0 对实验定义进行了一些修改，需要对旧实验进行更新后才能继续使用。

在导出实验文件的同一目录下，请运行以下命令：
```

2021-06-28 02:04 UTC, qiancai commented on docs/upgrade-to-2.0.md
> +如果在升级过程中遇到任何问题，我们很乐意帮助解决。请将命令行输出一并提交至 [slack](https://cloud-native.slack.com/archives/C0193VAV272) 或新建 github issue 。
```suggestion
如果在升级过程中遇到任何问题，请将命令行输出提交至 [slack](https://cloud-native.slack.com/archives/C0193VAV272) 或在 Github 上新建一个 [issue](https://github.com/pingcap/chaos-mesh/issues)。感谢你的反馈，Chaos Mesh 团队很乐意帮助解决。
```

2021-06-29 03:27 UTC, qiancai requested changes
@AsterNighT PTAL. Thanks!

2021-06-29 03:33 UTC, AsterNighT commented on docs/upgrade-to-2.0.md
> +我们提供了一个升级脚本来简化升级过程。你可以在 tools/schedule-migration 找到它们。为使用这一工具，我们建议您将 Chaos Mesh 项目克隆至本地，或是从（这里应该有一个打包好的链接）获取。你需要拥有 go 编译环境以编译升级工具。
应该会在 mirror.chaosmesh 之类的地方。没啥注意事项，就是得按下面讲的顺序进行操作。

2021-06-29 03:34 UTC, AsterNighT commented on docs/upgrade-to-2.0.md
> +
没有，这些yaml是直接从集群中导出的，和旧版无关。当然也可以手动用工具升级旧版yaml。我加一栏吧。

2021-06-29 03:39 UTC, AsterNighT commented
这个文档是新增的，不在原来的那个list里， @g1eny0ung 是不是要把它加进list里面？

2021-06-29 09:57 UTC, g1eny0ung commented
> 这个文档是新增的，不在原来的那个list里， @g1eny0ung 是不是要把它加进list里面？

我加一下。

2021-07-05 02:40 UTC, qiancai reviewed
@AsterNighT PTAL

2021-07-05 02:40 UTC, qiancai commented on docs/upgrade-to-2.0.md
> +本文将介绍从 Chaos Mesh 1.x 升级至 2.0 的详细步骤。Chaos Mesh 2.0 引入了一些新功能，并修复了许多问题。Chaos Mesh 2.0 重构了一部分代码，因此需要做一些额外的操作从 Chaos Mesh 1.x 来升级到 2.0。
```suggestion
本文介绍从 Chaos Mesh 1.x 升级至 2.0 的详细步骤。Chaos Mesh 2.0 引入了一些新功能，并修复了许多问题。Chaos Mesh 2.0 重构了一部分代码，因此需要做一些额外的操作从 Chaos Mesh 1.x 升级到 2.0。
```

2021-07-05 02:40 UTC, qiancai commented on docs/upgrade-to-2.0.md
> +为使用这一工具，我们建议将 Chaos Mesh 项目克隆至本地，或是从（这里应该有一个打包好的链接）获取。你需要拥有 Go 编译环境用于编译升级工具。
```suggestion
要获取升级工具，建议将 Chaos Mesh 项目克隆至本地，或是从（这里应该有一个打包好的链接）下载，然后查看 tools/schedule-migration 目录。
```

2021-07-05 02:40 UTC, qiancai commented on docs/upgrade-to-2.0.md
> +为使用这一工具，我们建议将 Chaos Mesh 项目克隆至本地，或是从（这里应该有一个打包好的链接）获取。你需要拥有 Go 编译环境用于编译升级工具。
“我们”通常指代不清我们到底是谁，同时比较主观，因此在技术文档中我们要尽量避免使用 “我们”。

2021-07-05 02:40 UTC, qiancai commented on docs/upgrade-to-2.0.md
> +当然，你也可以使用工具手动升级旧版 YAML。将工具目录下的 `main.go` 编译为可执行文件，接着运行：
```suggestion
此外，你也可以使用工具手动升级旧版 YAML。将 tools 目录下的 `main.go` 编译为可执行文件，然后运行：
```

2021-07-05 02:40 UTC, qiancai commented on docs/upgrade-to-2.0.md
> +为了简化升级过程，Chaos Mesh 2.0 为你提供了升级工具（位于 tools/schedule-migration 路径下），包括一个 Bash 脚本文件以及用于将旧版 YAML 更新为新版 YAML 的 Go 程序。
```suggestion
CRD 在 Chaos Mesh 2.0 中发生了变化，旧版本实验的 YAML 文件无法在 Chaos Mesh 2.0 上运行。如果希望继续使用旧版本实验的 YAML 文件，则需要将它们导出，修改并在升级后重新导入。

为了简化升级过程，Chaos Mesh 2.0 提供了以下升级工具：
- `migrate.sh`：用于自动导出并升级实验 YAML 文件、升级 CRD、导入升级后的YAML 文件。
- `main.go`：用于将手动指定的旧版 YAML 更新为新版 YAML。要使用此升级工具，你需要拥有 Go 编译环境，并将 `main.go` 编译为可执行文件。
```

2021-07-05 02:40 UTC, qiancai commented on docs/upgrade-to-2.0.md
> +由于 CRD 在 Chaos Mesh 2.0 中发生了变化，旧版本的实验无法在 Chaos Mesh 2.0 上运行。如果希望继续使用这些实验，则需要将它们导出，修改并在升级后重新导入。升级脚本提供了这些功能。为了方便演示，我们假设这一脚本就在当前目录下。在运行之前，请确保当前用户有足够的权限访问集群：
```suggestion
要自动导出并升级实验，你可以使用升级工具 `migrate.sh`。在运行之前，请确保当前用户有足够的权限访问集群。

假设 `migrate.sh` 位于当前目录下，请执行以下命令导出并升级实验：
```

2021-07-05 02:40 UTC, qiancai commented on docs/upgrade-to-2.0.md
> +## 导出并升级实验
```suggestion
## 第 1 步：导出并升级实验
```

2021-07-05 02:40 UTC, qiancai commented on docs/upgrade-to-2.0.md
> +## 升级 CRD
```suggestion
## 第 2 步：升级 CRD
```

2021-07-05 02:40 UTC, qiancai commented on docs/upgrade-to-2.0.md
> +## 升级 Chaos Mesh
```suggestion
## 第 3 步：升级 Chaos Mesh
```

2021-07-05 02:40 UTC, qiancai commented on docs/upgrade-to-2.0.md
> +## 导入实验
```suggestion
## 第 4 步：导入实验
```

2021-07-05 06:16 UTC, YangKeao commented on docs/upgrade-to-2.0.md
> +- `main.go`：用于将手动指定的旧版 YAML 更新为新版 YAML。要使用此升级工具，你需要拥有 Go 编译环境，并将 `main.go` 编译为可执行文件。
@cwen0 这个工具我们能否提供二进制发行的版本？让用户编译可能不太妙

2021-07-06 10:20 UTC, cwen0 commented on docs/upgrade-to-2.0.md
> +- `main.go`：用于将手动指定的旧版 YAML 更新为新版 YAML。要使用此升级工具，你需要拥有 Go 编译环境，并将 `main.go` 编译为可执行文件。
这个当然可以呀

2021-07-07 08:26 UTC, cwen0 commented on docs/upgrade-to-2.0.md
> +- `main.go`：用于将手动指定的旧版 YAML 更新为新版 YAML。要使用此升级工具，你需要拥有 Go 编译环境，并将 `main.go` 编译为可执行文件。
我增加一下

2021-07-27 05:52 UTC, Colstuwjx commented on docs/extend-chaos-daemon-interface.md
> +   在 HelloWorldChaos 中，恢复过程什么都没有做。这是因为 HelloWorldChaos 是一个 OneShot 实验。如果你的新实验需要恢复，你应该在其中实现相关逻辑。
建议是否把 OneShot 也翻译一下？
```suggestion
   在 HelloWorldChaos 中，恢复过程什么都没有做。这是因为 HelloWorldChaos 是一个一次过的实验。如果你的新实验需要恢复，你应该在其中实现相关逻辑。
```

2021-07-27 10:38 UTC, cwen0 commented on docs/inspect-chaos-experiment.md
> +  :::
这个应该没有空格

2021-07-27 10:59 UTC, YangKeao commented on docs/inspect-chaos-experiment.md
> +  :::
Fixed.

2021-07-28 03:10 UTC, cwen0 approved these changes
LGTM

2021-07-28 03:13 UTC, cwen0 commented on docs/simulate-http-chaos-on-kubernetes.md
> +```yaml
这里是不是需要个 tab @qiancai

2021-07-28 03:13 UTC, cwen0 commented on docs/simulate-http-chaos-on-kubernetes.md
> +```yaml
ditto

2021-07-28 03:13 UTC, cwen0 commented on docs/simulate-http-chaos-on-kubernetes.md
> +```bash
ditto

2021-07-28 05:31 UTC, qiancai commented on docs/upgrade-to-2.0.md
> +- `schedule-migration`：用于将手动指定的旧版 YAML 更新为新版 YAML。
```suggestion
- `schedule-migration`：用于将手动指定的旧版 YAML 文件更新为新版 YAML 文件。
```

2021-07-29 11:29 UTC, cwen0 commented
@qiancai PTAL again! Thanks!

2021-07-29 12:53 UTC, cwen0 commented
/merge

2021-07-29 12:54 UTC, merged