docs: add chaosd download
chaos-mesh/website-zh pull request #40
Opened 2021-06-29 08:55 UTC by WangXiangUSTC

Signed-off-by: xiang <xiang13225080@163.com>

增加 chaosd 的下载说明。

2021-06-29 14:58 UTC, qiancai commented on docs/chaosd-overview.md
> +需要 Linux 系统内核 2.17 及以上版本。
```suggestion
Linux 系统内核必须为 2.17 及以上版本。
```

2021-06-29 14:58 UTC, qiancai commented on docs/chaosd-overview.md
> +指定要下载的版本，例如 v1.0.0：
有没有命令可以查支持的版本有哪些？可以在文档这里提供下吗？不然用户可能不太知道可以指定哪些版本。

2021-06-29 14:58 UTC, qiancai commented on docs/chaosd-overview.md
> +### 下载
请问该组件只能单独下载后才能使用吗？如果该组件是用户一定会用到的组件，是否可以在 “使用 Helm 安装“ 那里一起下载安装了呢？

2021-06-30 02:27 UTC, WangXiangUSTC commented on docs/chaosd-overview.md
> +### 下载
只能单独下载使用，不是必须的组件，只在物理机环境下使用。不能用 helm 安装

2021-06-30 02:28 UTC, WangXiangUSTC commented on docs/chaosd-overview.md
> +指定要下载的版本，例如 v1.0.0：
加了一个 releases 的链接

2021-06-30 07:23 UTC, cwen0 commented on docs/chaosd-overview.md
> +接下来就可以使用 Chaosd 了。
如果想要把 chaosd 加入到 PATH 呢？

2021-07-01 03:34 UTC, WangXiangUSTC commented on docs/chaosd-overview.md
> +接下来就可以使用 Chaosd 了。
加了描述

2021-07-05 02:54 UTC, qiancai requested changes

2021-07-05 02:54 UTC, qiancai commented on docs/chaosd-overview.md
> +### 下载
好的，了解了。可以把本文开头那句话 “Chaosd 是 Chaos Mesh 提供的一款混沌工程测试工具，用于在物理机环境上注入故障，并提供故障恢复功能。”，这里补充下吗？ 比如 “Chaosd 是 Chaos Mesh 提供的一款混沌工程测试工具（需要单独下载），用于在物理机环境上注入故障，并提供故障恢复功能。”在下载这个词这里链接到这个下载章节。

2021-07-05 02:54 UTC, qiancai commented on docs/chaosd-overview.md
> +
下面步骤需要顺序执行，麻烦可以改成 1, 2, 3, 4 这样的吗，可以帮助用户更清晰地执行这些步骤，比如：
1. 执行以下命令将要下载的 Chaosd 版本设置为环境变量。
......
2. 执行以下命令下载 Chaosd：
......
3. 解压 Chaosd 文件并转移到 /usr/local 目录下：
......
4. 将 Chaosd 目录加到环境变量 `PATH` 中：
......

2021-07-05 03:47 UTC, WangXiangUSTC commented on docs/chaosd-overview.md
> +
已经修改

2021-07-05 03:47 UTC, WangXiangUSTC commented on docs/chaosd-overview.md
> +### 下载
已经修改

2021-07-06 10:30 UTC, qiancai commented on docs/chaosd-overview.md
> +   通过 [releases](https://github.com/chaos-mesh/chaosd/releases) 查看所有已发布版本，然后指定要下载的版本，例如 v1.0.0：
```suggestion
1. 将要下载的 Chaosd 版本设置为环境变量，例如 v1.0.0：
```

2021-07-06 10:30 UTC, qiancai commented on docs/chaosd-overview.md
> +
```suggestion

如果要查看所有已发布的 Chaosd 版本，请参阅 [releases](https://github.com/chaos-mesh/chaosd/releases) 。

```

2021-07-06 10:30 UTC, qiancai commented on docs/chaosd-overview.md
> +2. 下载 Chaosd
```suggestion
2. 下载 Chaosd。
```

2021-07-06 10:30 UTC, qiancai commented on docs/chaosd-overview.md
> +3. 解压 Chaosd 文件并转移到 /usr/local 目录下
```suggestion
3. 解压 Chaosd 文件并转移到 /usr/local 目录下。
```

2021-07-06 10:30 UTC, qiancai commented on docs/chaosd-overview.md
> +4. 将 Chaosd 目录加到环境变量 `PATH` 中
```suggestion
4. 将 Chaosd 目录加到环境变量 `PATH` 中。
```

2021-07-06 10:30 UTC, qiancai commented on docs/chaosd-overview.md
> +2. 下载 Chaosd
这些步骤都是完整的句子，而不是标题，所以需要以句号结尾。

2021-07-06 10:30 UTC, qiancai commented on docs/chaosd-overview.md
> +接下来就可以使用 Chaosd 了。
“接下来就可以使用 Chaosd 了。”可以删了吗？感觉好像不写也行。

2021-07-09 03:39 UTC, WangXiangUSTC commented
@qiancai @cwen0 PTAL again

2021-07-12 05:53 UTC, qiancai reviewed
@WangXiangUSTC PTAL Thanks

2021-07-12 05:53 UTC, qiancai commented on docs/chaosd-overview.md
> +   通过 [releases](https://github.com/chaos-mesh/chaosd/releases) 查看所有已发布版本，然后指定要下载的版本，例如 v1.0.0：
```suggestion
```

2021-07-12 05:53 UTC, qiancai commented on docs/chaosd-overview.md
> +   执行以下命令：
```suggestion
2. 下载 Chaosd：
```

2021-07-12 05:53 UTC, qiancai commented on docs/chaosd-overview.md
> +   执行以下命令：
```suggestion
3. 解压 Chaosd 文件并转移到 /usr/local 目录下：
```

2021-07-12 05:53 UTC, qiancai commented on docs/chaosd-overview.md
> +   执行以下命令：
```suggestion
4. 将 Chaosd 目录加到环境变量 `PATH` 中：
```

2021-07-12 05:53 UTC, qiancai commented on docs/chaosd-overview.md
> +接下来就可以使用 Chaosd 了。
@WangXiangUSTC 请问可以删了 “”， 然后把 “运行模式” 这个小节挪到这里吗，这样呈现的顺序就是先下载和部署，再谈运行模式，是不是会符合实际使用顺序些呢？

2021-07-12 05:53 UTC, qiancai commented on docs/chaosd-overview.md
> +   通过 [releases](https://github.com/chaos-mesh/chaosd/releases) 查看所有已发布版本，然后指定要下载的版本，例如 v1.0.0：
这句话和下面的 “如果要查看所有已发布的 Chaosd 版本 ..." 这句话意思重复了，麻烦请删下。

2021-07-12 06:07 UTC, WangXiangUSTC commented
@qiancai PTAL again

2021-07-12 06:14 UTC, qiancai approved these changes

2021-07-12 06:16 UTC, qiancai commented
LGTM

2021-07-13 06:23 UTC, cwen0 approved these changes
LGTM

2021-07-13 06:24 UTC, cwen0 commented
/merge

2021-07-13 06:25 UTC, merged